[project]
name = "gemsmarl"
version = "0.1.0"
description = "My Reinforcement Learning Algorithm Library"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "moviepy>=2.2.1",
    "torchrl>=0.8.1",
    "vmas>=1.5.1",
    "wandb>=0.22.3",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"